// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adqirfewyfmiehinhapp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkcWlyZmV3eWZtaWVoaW5oYXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2Nzk1NjMsImV4cCI6MjA1MzI1NTU2M30.0iHIV-UWhI4b2xlhe5xD3-Rj-mOrg3OpmCa7HLnMRR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);